name: FitnessGropArgentina
favicon: null
layout_spectrum: 0.3267943514510989
typography_spectrum: 0.3588653886690736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4704882809892297
  lightness: 0.07590008317492902
  saturation: 0.0010250979103147984
  rhythmicContrast: 0.7023729968350381
purpose: []
